### ISSUE TITLE
Unable to Load ktx2 textures at run time in unity iOS editor

### ISSUE THREAD

**Issue by hggz** [atteneder/KtxUnityDemo#4]
Hey all, I'm trying to load my ktx2 textures using the async samples provided, from within the Unity Editor which is set to use the iOS player. Every time I do those it fails with an exception:

EntryPointNotFound

Is this not possible? Should I be using another configuration? The assemblies for ktunity and ktunity.editor are added.

I'm on unity 2019.3.1 also. Thanks!

**Comment by atteneder** [comment]
Hi @hggz ,

Are you using this project (KtxUnityDemo) actually?

How exactly did you install the KtxUnity package?

**Comment by atteneder** [comment]
closing in favor of https://github.com/atteneder/KtxUnityDemo/issues/4
